apiVersion: v1
kind: ConfigMap
metadata:
  name: "user-bets"
  labels:
    app: "user-bets"
  namespace: development
data:
  RABBIT_HOST: "rabbitmq-rabbitmq"
  RABBIT_PORT: "5672"
  MONGO_HOST: "mongodb-mongodb"
  MONGO_PORT: "27017"
  ENV_SPRING: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: "user-bets"
  namespace: development
type: Opaque
data:
  MONGO_USER: c2Vuc2VkaWEtYmV0
  MONGO_PASS: YmV0QDIwMTg=
  RABBIT_USER: c2Vuc2VkaWEtYmV0
  RABBIT_PASS: YmV0QDIwMTg=
---
apiVersion: v1
kind: Service
metadata:
  name: "user-bets"
  labels:
    app: "user-bets"
  namespace: development
spec:
  selector:
    app: "user-bets"
  ports:
  - name: http
    port: 9999
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: user-bets
  name: user-bets
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-bets
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-bets
        tier: backend
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              key: RABBIT_HOST
              name: user-bets
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              key: RABBIT_PORT
              name: user-bets
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOST
              name: user-bets
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: user-bets
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: ENV_SPRING
              name: user-bets
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              key: RABBIT_USER
              name: user-bets
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              key: RABBIT_PASS
              name: user-bets
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              key: MONGO_USER
              name: user-bets
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              key: MONGO_PASS
              name: user-bets
        image: gcr.io/sensedia-bet/user_bets:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: user-bets
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
